# Assignment-3

This notebook contains the coding questions to test the proficiency in `Pandas` library in python.

### Date: 30th August, 2026

### Steps to solve and upload the assignment 

- Download the notebook in your local machine.
- Solve the questions in the notebook and save it.
- Rename the file as `Assignment-03-<your_name>_<your_surname>.ipynb`. For example if your name is Dipika Chopra then name the file as `Assignment-03-Dipika_Chopra.ipynb`.
- Upload the solved notebook in your github repo under the folder **Assignment-3**.
- Upload the solved notebook in the google drive location: https://drive.google.com/drive/folders/1QVDdoiNNG1XRol0nFZIE7DHtQlHR0t6c?usp=drive_link 
<h3><span style="color:red"> Deadline: 20th September, 2026 </span></h3>

Use the `population_by_county.csv` file in the folder to complete the tasks.

**NOTE: TRY TO DO ALL THE TASKS IN ONE LINE OF PANDAS CODE.**

In [1]:
import pandas as pd

#### 1. Import pandas and read in the `population_by_county.csv` file into a dataframe called `pop`.

In [8]:
# Write your code here
pop = pd.read_csv("./population_by_county.csv")

#### 2. Show the head of the dataframe, Also show top 8 rows of the dataframe using head

In [15]:
# Write your code here

print("header:", pop.head())

print("Top 8:", pop.head(8))

header:              County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054
Top 8:              County           State  2010Census  2017PopEstimate
0  Abbeville County  South Carolina       25417            24722
1     Acadia Parish       Louisiana       61773            62590
2   Accomack County        Virginia       33164            32545
3        Ada County           Idaho      392365           456849
4      Adair County            Iowa        7682             7054
5      Adair County        Kentucky       18656            19485
6      Adair County        Missouri       25607            25377
7      Adair County        Oklahoma       22683            21909

#### 3. What are the column names?

In [19]:
# Write your code here
print(pop.columns)

Index(['County', 'State', '2010Census', '2017PopEstimate'], dtype='object')

#### 4. How many States are represented in this data set?  
<em>Note: the data includes the `District of Columbia`</em>

In [27]:
# Write your code here
print(pop['State'].nunique())

51

#### 5. Get a list or array of all the states in the data set.

In [28]:
# Write your code here
states = pop['State'].unique()
states

array(['South Carolina', 'Louisiana', 'Virginia', 'Idaho', 'Iowa',
       'Kentucky', 'Missouri', 'Oklahoma', 'Colorado', 'Illinois',
       'Indiana', 'Mississippi', 'Nebraska', 'North Dakota', 'Ohio',
       'Pennsylvania', 'Washington', 'Wisconsin', 'Vermont', 'Minnesota',
       'Florida', 'North Carolina', 'California', 'New York', 'Wyoming',
       'Michigan', 'Alaska', 'Maryland', 'Kansas', 'Tennessee', 'Texas',
       'Maine', 'Arizona', 'Georgia', 'Arkansas', 'New Jersey',
       'South Dakota', 'Alabama', 'Oregon', 'West Virginia',
       'Massachusetts', 'Utah', 'Montana', 'New Hampshire', 'New Mexico',
       'Rhode Island', 'Nevada', 'District of Columbia', 'Connecticut',
       'Hawaii', 'Delaware'], dtype=object)

#### 6. What are the five most common County names in the U.S.?

In [33]:
# Write your code here
pop['County'].value_counts().head()

County
Washington County    30
Jefferson County     25
Franklin County      24
Lincoln County       23
Jackson County       23
Name: count, dtype: int64

#### 7. What are the top 5 most populated Counties according to the 2010 Census?

In [44]:
# Write your code here
pop.sort_values(['2010Census'],ascending=False).head().reset_index()['County']

0    Los Angeles County
1           Cook County
2         Harris County
3       Maricopa County
4      San Diego County
Name: County, dtype: object

#### 8. What are the top 5 most populated States according to the 2010 Census?

In [57]:
# Write your code here
pop.sort_values(['2010Census'],ascending=False).head().reset_index()['State']

0    California
1      Illinois
2         Texas
3       Arizona
4    California
Name: State, dtype: object

#### 9. How many Counties have 2010 populations greater than 1 million?

In [73]:
# Write your code here

pop.query('`2010Census` > 1_000_000')

print(len(pop.query('`2010Census` > 1_000_000')))

(pop['2010Census'] > 1_000_000).sum()

39

np.int64(39)

#### 10. How many Counties don't have the word "County" in their name?

In [92]:
# Write your code here

len(pop[~pop['County'].str.contains('County')])

135

#### 11. Add a column that calculates the percent change between the 2010 Census and the 2017 Population Estimate

In [102]:
# Write your code here
pop_copy =  pop.copy()
perc_change_2010_2017 = ((pop_copy['2017PopEstimate'] - pop_copy['2010Census']) / pop_copy['2010Census'])* 100

pop_copy['perc_change_2010_2017'] = perc_change_2010_2017

pop_copy.head()

,County,State,2010Census,2017PopEstimate,perc_change_2010_2017
0,Abbeville County,South Carolina,25417,24722,-2.734390
1,Acadia Parish,Louisiana,61773,62590,1.322584
2,Accomack County,Virginia,33164,32545,-1.866482
3,Ada County,Idaho,392365,456849,16.434697
4,Adair County,Iowa,7682,7054,-8.174954

#### 12. What States have the highest estimated percent change between the 2010 Census and the 2017 Population Estimate?

**NOTE:** This will take several lines of code, as it requires a recalculation of Percent Change.

In [101]:
# Write your code here

pop_copy.sort_values(['perc_change_2010_2017'], ascending=False).head().reset_index()

,index,County,State,2010Census,2017PopEstimate,perc_change_2010_2017
0,1861,McKenzie County,North Dakota,6360,12724,100.062893
1,1720,Loving County,Texas,82,134,63.414634
2,3060,Williams County,North Dakota,22398,33349,48.892758
3,1230,Hays County,Texas,157107,214485,36.521606
4,2944,Wasatch County,Utah,23530,32106,36.447089